#!/usr/bin/env sh

# does not kickoff sxhkd, as the bspwm Nix derivation does already.

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            1
bspc config window_gap              6

bspc config split_ratio             0.54
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config remove_diabled_monitors true

bspc config focused_border_color "#b8c8e3"
bspc config normal_border_color "#000000"

# Lock screen of sorts
slock

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar -c /env/dotfiles/polybar mybar
