#!/usr/bin/env sh

#   _
#  | |
#  | |__  ___ _ ____      ___ __ ___  _ __ ___
#  | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#  | |_) \__ \ |_) \ V  V /| | | | | | | | (__
#  |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#            | |
#            |_|

# does not kickoff sxhkd, as the bspwm Nix derivation does already.

bspc monitor primary -d I II III IV V VI VII VIII IX X

bspc config border_width              2
bspc config window_gap                10

bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config remove_diabled_monitors   true
bspc config remove_unplugged_monitors true

bspc config focused_border_color      "#ff8c80"
bspc config normal_border_color       "#000000"

# adopt any orphan nodes from old sessions #
bspc wm -o

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar -c /env/dotfiles/polybar mybar

picom --config /env/dotfiles/picom.conf

redshift -b 1.0:0.7 -l 41.64801:-80.14641 -t 5500:4000 &
