#!/usr/bin/env sh

# https://linuxconfig.org/how-to-configure-your-monitors-with-xrandr-in-linux
# enable only the default monitor #

run() {
  xrandr \
    --output DP-1 \
    --off \
    --output DP-2 \
    --off \
    --output eDP-1 \
    --auto \
    --output eDP-1 \
    --primary \
    --dpi 96
  removeMonitor DP-1
  removeMonitor DP-2
  wmRestart
}

run
