#!/usr/bin/env sh

# enable the dual vert monitors#
run() {
  xrandr \
    --output eDP-1 \
    --off \
    --output DP-1 \
    --primary \
    --mode 3840x2160 \
    --rate 60.00 \
    --rotate 'left' \
    --dpi 150 \
    --output DP-2 \
    --mode 3840x2160 \
    --rate 60.00 \
    --rotate 'left' \
    --right-of DP-1 \
    --dpi 150
  removeMonitor eDP-1
  wmRestart
}

run
