#!/usr/bin/env sh
# NOTE: xrandr --listactivemonitors also looks for existing monitors

# remove monitor from bspwm #
run() {
  if [[ $(bspc query -M --names) == *"$1"* ]]; then
    bspc monitor $1 -r
  fi
}

run $1
