#!/usr/bin/env sh

# remove monitor from bspwm #
run() {
  # NOTE: xrandr --listactivemonitors also looks for existing monitors
  if [[ $(bspc query -M --names) == *"$1"* ]]; then
    bspc monitor $1 -r
  fi
}

run $1
