#!/usr/bin/env sh

# enable the single panoramic monitor #
single_monitor() {
  xrandr \
    --output eDP-1 \
    --off \
    --output DP-1 \
    --primary \
    --mode 1920x1080 \
    --rate 60.00 \
    --dpi 120
  remove_monitor eDP-1
  wm_restart
}
