#!/usr/bin/env sh

# enable the dual vert monitors#
run() {
  xrandr \
    --output eDP-1 \
    --off \
    --output DP-1 \
    --primary \
    --mode 1920x1080 \
    --rate 60.00 \
    --rotate 'right' \
    --dpi 120
  removeMonitor eDP-1
  wmRestart
}

run
