#!/usr/bin/env sh

run() {
  rofi -show window \
    -matching fuzzy \
    -display-window ">" \
    -tokenize \
    -theme "/env/dotfiles/rofi.rasi" \
    -disable-history \
    -hide-scrollbar
}

run
